local mod = get_mod("ovenproof_scoreboard_plugin")

-- ########################
-- Row Categorization
-- ########################
mod.scoreboard_rows = {
--Rows exploration_tier_0
	{name = "total_material_pickups",
		text = "row_total_material_pickups",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "exploration_tier_0",
	},
	{name = "ammo_1",
		text = "row_ammo_1",
		group = "group_1",
		validation = "DESC",
		iteration = "ADD",
		summary = {
			"ammo_percent",
			"ammo_wasted_percent",
		},
		setting = "exploration_tier_0",
	},
	{name = "ammo_percent",
		text = "row_ammo_percent",
		group = "group_1",
		validation = "DESC",
		iteration = "ADD",
		parent = "ammo_1",
		setting = "exploration_tier_0",
	},
	{name = "ammo_wasted_percent",
		text = "row_ammo_wasted",
		group = "group_1",
		validation = "DESC",
		iteration = "ADD",
		parent = "ammo_1",
		setting = "exploration_tier_0",
	},
	{name = "ammo_2",
		text = "row_ammo_2",
		group = "group_1",
		validation = "DESC",
		iteration = "ADD",
		summary = {
			"ammo_grenades",
			"ammo_crates",
		},
		setting = "exploration_tier_0",
	},
	{name = "ammo_grenades",
		text = "row_ammo_grenades",
		validation = "DESC",
		iteration = "ADD",
		group = "group_1",
		parent = "ammo_2",
		setting = "exploration_tier_0",
	},
	{name = "ammo_crates",
		text = "row_ammo_crates",
		validation = "DESC",
		iteration = "ADD",
		group = "group_1",
		parent = "ammo_2",
		setting = "exploration_tier_0",
	},
	{name = "blank_1",
		text = "row_blank",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "exploration_tier_0",
		is_text = true,
	},
--Rows defense_tier_0
	{name = "total_health",
		text = "row_total_health",
		validation = "DESC",
		iteration = "ADD",
		summary = {
			"total_damage_taken",
			"total_health_stations",
		},
		group = "group_1",
		setting = "defense_tier_0",
	},
	{name = "total_damage_taken",
		text = "row_total_damage_taken",
		validation = "DESC",
		iteration = "DIFF",
		group = "group_1",
		parent = "total_health",
		setting = "defense_tier_0",
	},
	{name = "total_health_stations",
		text = "row_total_health_stations",
		validation = "DESC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_health",
		setting = "defense_tier_0",
	},
	{name = "total_friendly",
		text = "row_total_friendly",
		validation = "DESC",
		iteration = "ADD",
		summary = {
			"friendly_damage",
			"friendly_shots_blocked",
		},
		group = "group_1",
		setting = "defense_tier_0",
	},
	{name = "friendly_damage",
		text = "row_friendly_damage",
		validation = "DESC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_friendly",
		setting = "defense_tier_0",
	},
	{name = "friendly_shots_blocked",
		text = "row_friendly_shots_blocked",
		validation = "DESC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_friendly",
		setting = "defense_tier_0",
	},
	{name = "blank_2",
		text = "row_blank",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "defense_tier_0",
		is_text = true,
	},
	{name = "total_disabled_helped",
		text = "row_total_disabled_helped",
		validation = "DESC",
		iteration = "ADD",
		summary = {
			"total_times_disabled",
			"total_operatives_helped",
		},
		group = "group_1",
		setting = "defense_tier_0",
	},
	{name = "total_times_disabled",
		text = "row_total_times_disabled",
		validation = "DESC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_disabled_helped",
		setting = "defense_tier_0",
	},
	{name = "total_operatives_helped",
		text = "row_total_operatives_helped",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_disabled_helped",
		setting = "defense_tier_0",
	},
	{name = "total_downed_revived",
		text = "row_total_downed_revived",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_times_downed",
			"total_operatives_revived",
		},
		group = "group_1",
		setting = "defense_tier_0",
	},
	{name = "total_times_downed",
		text = "row_total_times_downed",
		validation = "DESC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_downed_revived",
		setting = "defense_tier_0",
	},
	{name = "total_operatives_revived",
		text = "row_total_operatives_revived",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_downed_revived",
		setting = "defense_tier_0",
	},
	{name = "total_killed_rescued",
		text = "row_total_killed_rescued",
		validation = "DESC",
		iteration = "ADD",
		summary = {
			"total_times_killed",
			"total_operatives_rescued",
		},
		group = "group_1",
		setting = "defense_tier_0",
	},
	{name = "total_times_killed",
		text = "row_total_times_killed",
		validation = "DESC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_killed_rescued",
		setting = "defense_tier_0",
	},
	{name = "total_operatives_rescued",
		text = "row_total_operatives_rescued",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_killed_rescued",
		setting = "defense_tier_0",
	},
	{name = "blank_3",
		text = "row_blank",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "defense_tier_0",
		is_text = true,
	},
--Rows offense_rates
	{name = "total_weakspot_rates",
		text = "row_total_weakspot_rates",
		validation = "ASC",
		iteration = "ADD",
		visible = true,
		summary = {
			"melee_wr",
			"ranged_wr",
			-- "companion_wr", -- Don't think dogs can headshot
		},
		group = "group_1",
		setting = "offense_rates",
	},
	--[[
	-- This causes a display bug
	{name = "total_weakspot_rates_with_blitz",
		text = "row_total_weakspot_rates_with_blitz",
		validation = "ASC",
		iteration = "ADD",
		visible = false,
		summary = {
			"melee_wr",
			"ranged_wr",
			"blitz_wr",
			-- "companion_wr", -- Don't think dogs can headshot
		},
		group = "group_1",
		setting = "offense_rates",
	},
	]]
	{name = "melee_wr",
		text = "row_melee_weakspot_rate",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_weakspot_rates",
		setting = "offense_rates",
	},
	{name = "ranged_wr",
		text = "row_ranged_weakspot_rate",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_weakspot_rates",
		setting = "offense_rates",
	},
	{
		name = "blitz_wr",
		text = "row_blitz_weakspot_rate",
		validation = "ASC",
		iteration = "ADD",
		visible = false,
		group = "group_1",
		parent = "total_weakspot_rates",
		setting = "offense_rates",
	},
	{name = "total_critical_rates",
		text = "row_total_critical_rates",
		validation = "ASC",
		iteration = "ADD",
		visible = true,
		summary = {
			"melee_cr",
			"ranged_cr",
			-- "companion_cr", -- Don't think dogs can crit
		},
		group = "group_1",
		setting = "offense_rates",
	},
	--[[
	-- This causes a display bug
	{name = "total_critical_rates_with_blitz",
		text = "row_total_critical_rates_with_blitz",
		validation = "ASC",
		iteration = "ADD",
		visible = false,
		summary = {
			"melee_cr",
			"ranged_cr",
			"blitz_cr",
			-- "companion_cr", -- Don't think dogs can crit
		},
		group = "group_1",
		setting = "offense_rates",
	},
	]]
	{name = "melee_cr",
		text = "row_melee_critical_rate",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_critical_rates",
		setting = "offense_rates",
	},
	{name = "ranged_cr",
		text = "row_ranged_critical_rate",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_critical_rates",
		setting = "offense_rates",
	},
	{
		name = "blitz_cr",
		text = "row_blitz_critical_rate",
		validation = "ASC",
		iteration = "ADD",
		visible = false,
		group = "group_1",
		parent = "total_critical_rates",
		setting = "offense_rates",
	},
	--[[{name = "total_dot_rates_1",
		text = "row_total_dot_rates_1",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"bleeding_cr",
			"burning_cr",
		},
		group = "group_1",
		setting = "offense_rates",
	},
	{name = "bleeding_cr",
		text = "row_bleeding_critical_rate",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_dot_rates_1",
		setting = "offense_rates",
	},
	{name = "burning_cr",
		text = "row_burning_critical_rate",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_dot_rates_1",
		setting = "offense_rates",
	},
	{name = "total_dot_rates_2",
		text = "row_total_dot_rates_2",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"warpfire_cr",
			"environmental_cr",
		},
		group = "group_1",
		setting = "offense_rates",
	},
	{name = "warpfire_cr",
		text = "row_warpfire_critical_rate",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_dot_rates_2",
		setting = "offense_rates",
	},
	{name = "environmental_cr",
		text = "row_environmental_critical_rate",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_dot_rates_2",
		setting = "offense_rates",
	},--]]
	{name = "blank_4",
		text = "row_blank",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "offense_rates",
		is_text = true,
	},
--Rows offense_tier_0
	{name = "total",
		text = "row_total",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_kills",
			"total_damage",
		},
		group = "group_1",
		setting = "offense_tier_0",
	},
	{name = "total_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total",
		setting = "offense_tier_0",
	},
	{name = "total_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total",
		setting = "offense_tier_0",
	},
	{name = "blank_5",
		text = "row_blank",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "offense_tier_0",
		is_text = true,
	},
--Rows offense_tier_1
	-- Melee Totals
	{name = "total_melee",
		text = "row_total_melee",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_melee_kills",
			"total_melee_damage",
		},
		group = "group_1",
		setting = "offense_tier_1",
	},
	{name = "total_melee_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_melee",
		setting = "offense_tier_1",
	},
	{name = "total_melee_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_melee",
		setting = "offense_tier_1",
	},
	-- Ranged Totals
	{name = "total_ranged",
		text = "row_total_ranged",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_ranged_kills",
			"total_ranged_damage",
		},
		group = "group_1",
		setting = "offense_tier_1",
	},
	{name = "total_ranged_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_ranged",
		setting = "offense_tier_1",
	},
	{name = "total_ranged_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_ranged",
		setting = "offense_tier_1",
	},
	-- Blitz Totals
	{
		name = "total_blitz",
		text = "row_total_blitz",
		validation = "ASC",
		iteration = "ADD",
		visible = false,
		summary = {
			"total_blitz_kills",
			"total_blitz_damage",
		},
		group = "group_1",
		setting = "offense_tier_1",
	},
	{
		name = "total_blitz_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		visible = false,
		group = "group_1",
		parent = "total_blitz",
		setting = "offense_tier_1",
	},
	{
		name = "total_blitz_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		visible = false,
		group = "group_1",
		parent = "total_blitz",
		setting = "offense_tier_1",
	},
	-- Companion Totals
	{name = "total_companion",
		text = "row_total_companion",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_companion_kills",
			"total_companion_damage",
		},
		group = "group_1",
		setting = "offense_tier_1",
	},
	{name = "total_companion_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_companion",
		setting = "offense_tier_1",
	},
	{name = "total_companion_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_companion",
		setting = "offense_tier_1",
	},
	-- Bleeding Totals
	{name = "total_bleeding",
		text = "row_total_bleeding",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_bleeding_kills",
			"total_bleeding_damage",
		},
		group = "group_1",
		setting = "offense_tier_1",
	},
	{name = "total_bleeding_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_bleeding",
		setting = "offense_tier_1",
	},
	{name = "total_bleeding_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_bleeding",
		setting = "offense_tier_1",
	},
	-- Burning
	{name = "total_burning",
		text = "row_total_burning",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_burning_kills",
			"total_burning_damage",
		},
		group = "group_1",
		setting = "offense_tier_1",
	},
	{name = "total_burning_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_burning",
		setting = "offense_tier_1",
	},
	{name = "total_burning_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_burning",
		setting = "offense_tier_1",
	},
	-- Warpfire
	{name = "total_warpfire",
		text = "row_total_warpfire",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_warpfire_kills",
			"total_warpfire_damage",
		},
		group = "group_1",
		setting = "offense_tier_1",
	},
	{name = "total_warpfire_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_warpfire",
		setting = "offense_tier_1",
	},
	{name = "total_warpfire_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_warpfire",
		setting = "offense_tier_1",
	},
	-- Toxin (Hive Scum)
	{name = "total_toxin",
		text = "row_total_toxin",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_toxin_kills",
			"total_toxin_damage",
		},
		group = "group_1",
		setting = "offense_tier_1",
	},
	{name = "total_toxin_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_toxin",
		setting = "offense_tier_1",
	},
	{name = "total_toxin_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_toxin",
		setting = "offense_tier_1",
	},
	-- Environmental
	{name = "total_environmental",
		text = "row_total_environmental",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_environmental_kills",
			"total_environmental_damage",
		},
		group = "group_1",
		setting = "offense_tier_1",
	},
	{name = "total_environmental_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_environmental",
		setting = "offense_tier_1",
	},
	{name = "total_environmental_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_environmental",
		setting = "offense_tier_1",
	},
	{name = "blank_6",
		text = "row_blank",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "offense_tier_1",
		is_text = true,
	},
--Rows offense_tier_2
	{name = "total_lesser",
		text = "row_total_lesser",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_lesser_kills",
			"total_lesser_damage",
		},
		group = "group_1",
		setting = "offense_tier_2",
	},
	{name = "total_lesser_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_lesser",
		setting = "offense_tier_2",
	},
	{name = "total_lesser_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_lesser",
		setting = "offense_tier_2",
	},
	{name = "total_elite",
		text = "row_total_elite",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_elite_kills",
			"total_elite_damage",
		},
		group = "group_1",
		setting = "offense_tier_2",
	},
	{name = "total_elite_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_elite",
		setting = "offense_tier_2",
	},
	{name = "total_elite_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_elite",
		setting = "offense_tier_2",
	},
	{name = "total_special",
		text = "row_total_special",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_special_kills",
			"total_special_damage",
		},
		group = "group_1",
		setting = "offense_tier_2",
	},
	{name = "total_special_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_special",
		setting = "offense_tier_2",
	},
	{name = "total_special_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_special",
		setting = "offense_tier_2",
	},
	{name = "total_boss",
		text = "row_total_boss",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"total_boss_kills",
			"total_boss_damage",
		},
		group = "group_1",
		setting = "offense_tier_2",
	},
	{name = "total_boss_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_boss",
		setting = "offense_tier_2",
	},
	{name = "total_boss_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "total_boss",
		setting = "offense_tier_2",
	},
	{name = "blank_7",
		text = "row_blank",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "offense_tier_2",
		is_text = true,
	},
--Rows offense_tier_3
	{name = "melee_lesser",
		text = "row_melee_lesser",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"melee_lesser_kills",
			"melee_lesser_damage",
		},
		group = "group_1",
		setting = "offense_tier_3",
	},
	{name = "melee_lesser_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "melee_lesser",
		setting = "offense_tier_3",
	},
	{name = "melee_lesser_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "melee_lesser",
		setting = "offense_tier_3",
	},
	{name = "ranged_lesser",
		text = "row_ranged_lesser",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"ranged_lesser_kills",
			"ranged_lesser_damage",
		},
		group = "group_1",
		setting = "offense_tier_3",
	},
	{name = "ranged_lesser_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "ranged_lesser",
		setting = "offense_tier_3",
	},
	{name = "ranged_lesser_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "ranged_lesser",
		setting = "offense_tier_3",
	},
	{name = "melee_elite",
		text = "row_melee_elite",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"melee_elite_kills",
			"melee_elite_damage",
		},
		group = "group_1",
		setting = "offense_tier_3",
	},
	{name = "melee_elite_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "melee_elite",
		setting = "offense_tier_3",
	},
	{name = "melee_elite_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "melee_elite",
		setting = "offense_tier_3",
	},
	{name = "ranged_elite",
		text = "row_ranged_elite",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"ranged_elite_kills",
			"ranged_elite_damage",
		},
		group = "group_1",
		setting = "offense_tier_3",
	},
	{name = "ranged_elite_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "ranged_elite",
		setting = "offense_tier_3",
	},
	{name = "ranged_elite_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "ranged_elite",
		setting = "offense_tier_3",
	},
	{name = "damage_special",
		text = "row_damage_special",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"damage_special_kills",
			"damage_special_damage",
		},
		group = "group_1",
		setting = "offense_tier_3",
	},
	{name = "damage_special_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "damage_special",
		setting = "offense_tier_3",
	},
	{name = "damage_special_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "damage_special",
		setting = "offense_tier_3",
	},
	{name = "disabler_special",
		text = "row_disabler_special",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"disabler_special_kills",
			"disabler_special_damage",
		},
		group = "group_1",
		setting = "offense_tier_3",
	},
	{name = "disabler_special_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "disabler_special",
		setting = "offense_tier_3",
	},
	{name = "disabler_special_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "disabler_special",
		setting = "offense_tier_3",
	},
	{name = "boss",
		text = "row_boss",
		validation = "ASC",
		iteration = "ADD",
		summary = {
			"boss_kills",
			"boss_damage",
		},
		group = "group_1",
		setting = "offense_tier_3",
	},
	{name = "boss_kills",
		text = "row_kills",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "boss",
		setting = "offense_tier_3",
	},
	{name = "boss_damage",
		text = "row_damage",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		parent = "boss",
		setting = "offense_tier_3",
	},
	{name = "blank_8",
		text = "row_blank",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "offense_tier_3",
		is_text = true,
	},
--Rows fun_stuff_01
	{name = "one_shots",
		text = "row_one_shots",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "fun_stuff_01",
	},
	{name = "highest_single_hit",
		text = "row_highest_single_hit",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "fun_stuff_01",
		is_text = true,
	},
	{name = "blank_9",
		text = "row_blank",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "fun_stuff_01",
		is_text = true,
	},
--Rows blanks
	{name = "blank_10",
		text = "row_blank",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "bottom_padding",
		is_text = true,
	},
	{name = "blank_11",
		text = "row_blank",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "bottom_padding",
		is_text = true,
	},
	{name = "blank_12",
		text = "row_blank",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "bottom_padding",
		is_text = true,
	},
	{name = "blank_13",
		text = "row_blank",
		validation = "ASC",
		iteration = "ADD",
		group = "group_1",
		setting = "bottom_padding",
		is_text = true,
	},
}
